version: "3"

volumes:
  redis:
  app:

services:

  nginx:
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    links:
      - redis
      - php
    depends_on:
      - php
    volumes:
      - redis:/var/lib/redis
      - app:/opt/app

  php:
    build: ./php/
    expose:
      - 9000
    links:
      - redis
    volumes:
      - redis:/var/lib/redis
      - ./app:/opt/app
    working_dir: /opt

  redis:
    image: redis:latest
    volumes:
      - redis:/var/lib/redis
